// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function CallMCP_tool(arg1, arg2, arg3) {
  return window['go']['main']['App']['CallMCP_tool'](arg1, arg2, arg3);
}

export function CancelMessage(arg1) {
  return window['go']['main']['App']['CancelMessage'](arg1);
}

export function ClearSessionMessages(arg1) {
  return window['go']['main']['App']['ClearSessionMessages'](arg1);
}

export function ConnectMCPServerFromConfig(arg1) {
  return window['go']['main']['App']['ConnectMCPServerFromConfig'](arg1);
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function EditAndResendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditAndResendMessage'](arg1, arg2, arg3, arg4);
}

export function GetDefaultStyles() {
  return window['go']['main']['App']['GetDefaultStyles']();
}

export function GetEnabledMCPTools() {
  return window['go']['main']['App']['GetEnabledMCPTools']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemFonts() {
  return window['go']['main']['App']['GetSystemFonts']();
}

export function GetThemeCSS(arg1) {
  return window['go']['main']['App']['GetThemeCSS'](arg1);
}

export function GetThemes() {
  return window['go']['main']['App']['GetThemes']();
}

export function MCPServerConnect(arg1) {
  return window['go']['main']['App']['MCPServerConnect'](arg1);
}

export function MCPServerCreate(arg1) {
  return window['go']['main']['App']['MCPServerCreate'](arg1);
}

export function MCPServerDelete(arg1) {
  return window['go']['main']['App']['MCPServerDelete'](arg1);
}

export function MCPServerDisconnect(arg1) {
  return window['go']['main']['App']['MCPServerDisconnect'](arg1);
}

export function MCPServerGetAllStatuses() {
  return window['go']['main']['App']['MCPServerGetAllStatuses']();
}

export function MCPServerGetStatus(arg1) {
  return window['go']['main']['App']['MCPServerGetStatus'](arg1);
}

export function MCPServerGetTools(arg1) {
  return window['go']['main']['App']['MCPServerGetTools'](arg1);
}

export function MCPServerList() {
  return window['go']['main']['App']['MCPServerList']();
}

export function MCPServerTest(arg1) {
  return window['go']['main']['App']['MCPServerTest'](arg1);
}

export function MCPServerUpdate(arg1) {
  return window['go']['main']['App']['MCPServerUpdate'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenThemeFolder() {
  return window['go']['main']['App']['OpenThemeFolder']();
}

export function PromptCreate(arg1) {
  return window['go']['main']['App']['PromptCreate'](arg1);
}

export function PromptDelete(arg1) {
  return window['go']['main']['App']['PromptDelete'](arg1);
}

export function PromptList() {
  return window['go']['main']['App']['PromptList']();
}

export function PromptSetDefault(arg1) {
  return window['go']['main']['App']['PromptSetDefault'](arg1);
}

export function PromptUpdate(arg1) {
  return window['go']['main']['App']['PromptUpdate'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['main']['App']['ReadImageAsBase64'](arg1);
}

export function ReorderSessions(arg1) {
  return window['go']['main']['App']['ReorderSessions'](arg1);
}

export function RetryFromUserMessage(arg1, arg2) {
  return window['go']['main']['App']['RetryFromUserMessage'](arg1, arg2);
}

export function RetryMessage(arg1, arg2) {
  return window['go']['main']['App']['RetryMessage'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveThemeCSS(arg1, arg2) {
  return window['go']['main']['App']['SaveThemeCSS'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function UpdateProvider(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateSession'](arg1, arg2, arg3, arg4, arg5);
}
