// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddProvider(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:boolean):Promise<model.Provider>;

export function CallMCP_tool(arg1:string,arg2:string,arg3:string):Promise<model.ToolCallResult>;

export function CancelMessage(arg1:number):Promise<void>;

export function ClearSessionMessages(arg1:number):Promise<void>;

export function ConnectMCPServerFromConfig(arg1:model.MCPServer):Promise<void>;

export function CreateSession(arg1:number,arg2:string,arg3:string):Promise<model.Session>;

export function DeleteProvider(arg1:number):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function GetDefaultStyles():Promise<string>;

export function GetEnabledMCPTools():Promise<Array<model.Tool>>;

export function GetHistory(arg1:number):Promise<Array<model.Message>>;

export function GetModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetProviders():Promise<Array<model.Provider>>;

export function GetSessions():Promise<Array<model.Session>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSystemFonts():Promise<Array<string>>;

export function MCPServerConnect(arg1:string):Promise<void>;

export function MCPServerCreate(arg1:model.MCPServer):Promise<model.MCPServer>;

export function MCPServerDelete(arg1:string):Promise<void>;

export function MCPServerDisconnect(arg1:string):Promise<void>;

export function MCPServerGetAllStatuses():Promise<Record<string, string>>;

export function MCPServerGetStatus(arg1:string):Promise<string>;

export function MCPServerGetTools(arg1:string):Promise<Array<model.MCPTool>>;

export function MCPServerList():Promise<Array<model.MCPServer>>;

export function MCPServerTest(arg1:model.MCPServer):Promise<model.MCPServerTestResult>;

export function MCPServerUpdate(arg1:model.MCPServer):Promise<model.MCPServer>;

export function OpenFileDialog():Promise<string>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function ReorderSessions(arg1:Array<number>):Promise<void>;

export function RetryFromUserMessage(arg1:number,arg2:string):Promise<string>;

export function RetryMessage(arg1:number,arg2:string):Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function SendMessage(arg1:number,arg2:string,arg3:Array<string>):Promise<string>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateProvider(arg1:number,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<void>;

export function UpdateSession(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;
